apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-kabal-integrasjon
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  kafka:
    pool: "{{ kafka_pool }}"
  azure:
    application:
      enabled: true
  env:
    - name: KLAGE_API_URL
      value: {{ kabal.url }}
    - name: KLAGE_API_SCOPE
      value: {{ kabal.scope }}
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4

  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: {{ kabal.host }}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
